### ISSUE TITLE
Invitation to Telegram group expired

### ISSUE THREAD

**Issue by bolaum** [datasciencebr/serenata-de-amor#63]
The invitation links for the Telegram group in the README files ([pt](../blob/master/README.md) and [en](../blob/master/README-en.md)) expired, returning the following error in the web interface:
```
Method: messages.checkChatInvite
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}
Stack: Error
    at Object.h [as invokeApi] (https://web.telegram.org/js/app.js:23:25735)
    at v (https://web.telegram.org/js/app.js:25:31282)
    at g (https://web.telegram.org/js/app.js:25:28732)
    at m (https://web.telegram.org/js/app.js:25:28121)
    at Object.f [as start] (https://web.telegram.org/js/app.js:25:31073)
    at new <anonymous> (https://web.telegram.org/js/app.js:26:13653)
    at Object.r [as instantiate] (https://web.telegram.org/js/app.js:11:21370)
    at https://web.telegram.org/js/app.js:12:15279
    at Object.link (https://web.telegram.org/js/app.js:16:12334)
    at https://web.telegram.org/js/app.js:11:6148
``` 

The Android app returns:
```
Sorry, this chat does not seem to exist.
```

**Comment by DavidPinho** [comment]
The same for me! I've tried to join the group via web interface and iOS app, but neither of them worked.
